// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7SnYXSYGQNIo8TNvd-ZyqjYWl8YQ9cY0',
    appId: '1:447849203813:web:850b2ed887c74c09839e8c',
    messagingSenderId: '447849203813',
    projectId: 'german-board-7fb50',
    authDomain: 'german-board-7fb50.firebaseapp.com',
    storageBucket: 'german-board-7fb50.firebasestorage.app',
    measurementId: 'G-1MQXEL2HTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa7lDofGod4xBcJiwMBdnSVIgeIrWmmXU',
    appId: '1:447849203813:android:2c5a345d6e8788e4839e8c',
    messagingSenderId: '447849203813',
    projectId: 'german-board-7fb50',
    storageBucket: 'german-board-7fb50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs9Zt5wLUWWWIpQK5WE0kOpSLj1_zAMJE',
    appId: '1:447849203813:ios:6711c180c44cf568839e8c',
    messagingSenderId: '447849203813',
    projectId: 'german-board-7fb50',
    storageBucket: 'german-board-7fb50.firebasestorage.app',
    androidClientId: '447849203813-jlar4fumgo0cp55pjv19o726sh00s0i2.apps.googleusercontent.com',
    iosClientId: '447849203813-pgainel99lg7bbht1m8ll0irrampr6fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.germanBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs9Zt5wLUWWWIpQK5WE0kOpSLj1_zAMJE',
    appId: '1:447849203813:ios:6711c180c44cf568839e8c',
    messagingSenderId: '447849203813',
    projectId: 'german-board-7fb50',
    storageBucket: 'german-board-7fb50.firebasestorage.app',
    androidClientId: '447849203813-jlar4fumgo0cp55pjv19o726sh00s0i2.apps.googleusercontent.com',
    iosClientId: '447849203813-pgainel99lg7bbht1m8ll0irrampr6fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.germanBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7SnYXSYGQNIo8TNvd-ZyqjYWl8YQ9cY0',
    appId: '1:447849203813:web:9258118cf4669218839e8c',
    messagingSenderId: '447849203813',
    projectId: 'german-board-7fb50',
    authDomain: 'german-board-7fb50.firebaseapp.com',
    storageBucket: 'german-board-7fb50.firebasestorage.app',
    measurementId: 'G-TCGMXJ3T41',
  );

}